### ISSUE TITLE
Nice project. Will you add a readme?

### ISSUE THREAD

**Issue by vasani-arpit** [leodutra/node-web-scrap#1]
Nice project. Are you planning to add readme? 

I am able to understand the code but I am unable to figure out start point and start script.

you can also explain overall idea here and I can make a PR with readme.

**Comment by leodutra** [comment]
Hi @vasani-arpit!
Sometimes I create these small node projects just to contain some code snippet which I had to use more than once. There are already 2 classes which are quite useful for generic simple scraping.
But if this is also interesting for you, I can add for sure. Maybe we can grow this into some nice library.

**Comment by vasani-arpit** [comment]
Thanks for the reply. I am planning to make something like this for https://github.com/vasani-arpit/Social-Media-Automation 

or create a node in https://github.com/n8n-io/n8n

I am not a pro in node.

I believe readmes are useful to get overall idea. even though we don't grow this as a library, If someone comes back to this repo after year or two then readme will easily refresh one's memory about what this library does.
